task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NHWC
  reverse_channels: false
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  target_device: null
  input_optimization: false
  input_data_layout: NHWC
  input_mean:
  - 123.68
  - 116.78
  - 103.94
  input_scale:
  - 0.003922
  - 0.003922
  - 0.003922
  runtime_options:
    tensor_bits: 8
    accuracy_level: 1
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 1
    advanced_options:calibration_iterations: 1
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: 0
  model_path: squeezenet.tflite
  model_id: cl-0020
  input_details: null
  output_details: null
  num_inputs: 1
metric:
  label_offset_pred: -1
model_info:
  metric_reference:
    accuracy_top1%: 57.5
  model_shortlist: null
