task_type: keypoint_detection
dataset_category: cocokpts
calibration_dataset: cocokpts
input_dataset: cocokpts
postprocess:
  save_output: false
preprocess:
  resize: 512
  crop: 512
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: null
  resize_with_pad: true
  pad_color:
  - 127
  - 127
  - 127
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 0.017125
  - 0.017507
  - 0.017429
  runtime_options:
    tensor_bits: 8
    accuracy_level: 1
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 12
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: 669,1384
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: null
  model_path: mobilenetv2_pan_spp_udp_512_20210617.onnx
  model_id: kd-7020expt
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 45.41
