preprocess:
  add_flip_image: false
  crop: 224
  data_layout: NCHW
  pad_color: 0
  resize: 256
  resize_with_pad: false
  reverse_channels: false
postprocess:
  label_offset_pred:
    0: 1
    1: 2
    2: 3
    3: 4
    4: 5
    5: 6
    6: 7
    7: 8
    8: 9
    9: 10
    10: 11
    11: 13
    12: 14
    13: 15
    14: 16
    15: 17
    16: 18
    17: 19
    18: 20
    19: 21
    20: 22
    21: 23
    22: 24
    23: 25
    24: 27
    25: 28
    26: 31
    27: 32
    28: 33
    29: 34
    30: 35
    31: 36
    32: 37
    33: 38
    34: 39
    35: 40
    36: 41
    37: 42
    38: 43
    39: 44
    40: 46
    41: 47
    42: 48
    43: 49
    44: 50
    45: 51
    46: 52
    47: 53
    48: 54
    49: 55
    50: 56
    51: 57
    52: 58
    53: 59
    54: 60
    55: 61
    56: 62
    57: 63
    58: 64
    59: 65
    60: 67
    61: 70
    62: 72
    63: 73
    64: 74
    65: 75
    66: 76
    67: 77
    68: 78
    69: 79
    70: 80
    71: 81
    72: 82
    73: 84
    74: 85
    75: 86
    76: 87
    77: 88
    78: 89
    79: 90
    80: 91
  formatter:
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
    src_indices:
    - 5
    - 4
  ignore_index: null
  normalized_detections: false
  resize_with_pad: false
  shuffle_indices: null
  squeeze_axis: null
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_mean: null
  input_scale: null
  input_optimization: true
  input_details:
  - name: input.1Net_IN
    shape:
    - 1
    - 3
    - 224
    - 224
    type: tensor(uint8)
  output_details:
  - name: '466'
    shape:
    - 1
    - 1000
    type: tensor(float)
  model_path: model/mobilenet_v2_tv.onnx
  session_name: onnxrt
  target_device: AM68A
task_type: classification
metric:
  label_offset_pred: null