
common:
    target_module: 'vision'
    task_type: 'segmentation'
    target_device: 'TDA4VM'
    # run_name can be any string, but there are some special cases:
    # {date-time} will be replaced with datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    # {model_name} will be replaced with the name of the model
    run_name: '{date-time}/{model_name}'

# Need to modify later according to the data loaders
dataset:
    # enable/disable dataset loading
    enable: True #False
    # max_num_files: [750, 250] #None
    # specify annotation prefix (of th annotation file) if neded - default is 'instances'.
    #annotation_prefix: 'stuff'
    
    # Semantic Segmentation Dataset Examples:
    # -------------------------------------
    # Example 1, (known datasets): 'widerface_detection', 'pascal_voc0712', 'coco_detection', 'udacity_selfdriving', 'tomato_detection', 'tiscapes2017_driving'
    # dataset_name: widerface_detection
    # -------------------------------------
    # Example 2, give a dataset name and input_data_path.
    # input_data_path could be a path to zip file, tar file, folder OR http, https link to zip or tar files
    # for input_data_path these are provided with this repository as examples:
    #    'http://software-dl.ti.com/jacinto7/esd/modelzoo/latest/datasets/tiscapes2017_driving.zip'
    #    'http://software-dl.ti.com/jacinto7/esd/modelzoo/latest/datasets/animal_detection.zip'
    # -------------------------------------
    # Example 3, give image folders with annotation files (require list with values for both train and val splits)
    # dataset_name: coco_detection
    # input_data_path: ["./data/projects/coco_detection/dataset/train2017",
    #                        "./data/projects/coco_detection/dataset/val2017"]
    # input_annotation_path: ["./data/projects/coco_detection/dataset/annotations/instances_train2017.json",
    #                        "./data/projects/coco_detection/dataset/annotations/instances_val2017.json"]
    # -------------------------------------
    dataset_name: tiscapes2017_driving
    input_data_path: "http://software-dl.ti.com/jacinto7/esd/modelzoo/latest/datasets/tiscapes2017_driving.zip"

training:
    # enable/disable training
    enable: True #False

    # Semantic segmentation model chosen can be changed here if needed
    # REGNETx800MF: fpn_aspp_regnetx800mf_edgeailite
    # UNET-MOBILENET: unet_aspp_mobilenetv2_tv_edgeailite
    # DEEPLABV3plus-MOBILENET: deeplabv3plus_mobilenetv2_tv_edgeailite

    model_name: 'deeplabv3plus_mobilenetv2_tv_edgeailite'

    #training_epochs: 15 #30
    #batch_size: 32 #8
    #learning_rate: 0.001
    #num_gpus: 0 1 2 3

compilation:
    # enable/disable compilation
    enable: True #False
    # tensor_bits: 8 #16 #32
