
common:
    target_module: 'vision'
    task_type: 'classification'
    target_device: 'TDA4VM'
    # run_name can be any string, but there are some special cases:
    # {date-time} will be replaced with datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    # {model_name} will be replaced with the name of the model
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    # max_num_files: [1000, 250] #None

    # Image Classification Dataset Examples:
    # -------------------------------------
    # Example 1, (known datasets): 'oxford_flowers102'
    # dataset_name: oxford_flowers102
    # -------------------------------------
    # Example 2, give a dataset_name and input_data_path.
    # input_data_path could be a path to zip file, tar file, folder OR http, https link to zip or tar files
    # for input_data_path these are provided with this repository as examples:
    #    'http://software-dl.ti.com/jacinto7/esd/modelzoo/latest/datasets/animal_classification.zip'
    # -------------------------------------
    dataset_name: animal_classification
    input_data_path: 'http://software-dl.ti.com/jacinto7/esd/modelzoo/latest/datasets/animal_classification.zip'

training:
    # enable/disable training
    enable: True #False

    # Image Classification model chosen can be changed here if needed
    # #'mobilenet_v2_lite_tv' #'mobilenet_v3_large_lite_tv' #'mobilenet_v3_small_lite_tv' #'regnet_x_400mf_tv' #'regnet_x_800mf_tv' #'regnet_x_1_6gf_tv'
    model_name: 'regnet_x_800mf_tv'

    training_epochs: 15 #30
    batch_size: 64 #8 #32
    # learning_rate: 0.005
    num_gpus: 0 #0 #1 #4

compilation:
    # enable/disable compilation
    enable: True #False
    tensor_bits: 8 #16 #32
