name: Self-hosted runner (past-ci)


on:
  workflow_call:
    inputs:
      framework:
        required: true
        type: string
      version:
        required: true
        type: string
      # Use this to control the commit to test against
      sha:
        default: 'main'
        required: false
        type: string

jobs:
  model-ci:
    name: Model CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_models_gpu
      slack_report_channel: "#transformers-ci-past-future"
      runner: past-ci
      docker: huggingface/transformers-${{ inputs.framework }}-past-${{ inputs.version }}-gpu
      ci_event: Past CI - ${{ inputs.framework }}-${{ inputs.version }}
    secrets: inherit

  deepspeed-ci:
    name: DeepSpeed CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_torch_cuda_extensions_gpu
      slack_report_channel: "#transformers-ci-past-future"
      runner: past-ci
      docker: huggingface/transformers-${{ inputs.framework }}-past-${{ inputs.version }}-gpu
      ci_event: Past CI - ${{ inputs.framework }}-${{ inputs.version }}
    secrets: inherit
