task_type: detection_3d
dataset_category: kitti_lidar_det_1class
calibration_dataset: kitti_lidar_det_1class
input_dataset: kitti_lidar_det_1class
postprocess: {}
preprocess: {}
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean: null
  input_scale: null
  runtime_options:
    advanced_options:quantization_scale_type: 1
    tensor_bits: 8
    accuracy_level: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 1
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    object_detection:meta_arch_type: 7
    object_detection:meta_layers_names_list: lidar_point_pillars_10k_496x432.prototxt
  model_path: lidar_point_pillars_10k_496x432_qat-p2.onnx
  model_id: 3dod-7100
  input_details: null
  output_details: null
  num_inputs: 1
metric:
  label_offset_pred: null
model_info:
  metric_reference: {}
  model_shortlist: 200
  compact_name: pointPillars-lidar-10000-1c-496x432
  shortlisted: true
