configs:
  cl-6360: vision/classification/imagenet1k/fbr-pycls/regnetx-200mf_config.yaml
  od-8020: vision/detection/coco/edgeai-mmdet/ssd_mobilenetv2_lite_512x512_20201214_model_config.yaml
  od-8200: vision/detection/coco/edgeai-mmdet/yolox_nano_lite_416x416_20220214_model_config.yaml
  od-8220: vision/detection/coco/edgeai-mmdet/yolox_s_lite_640x640_20220221_model_config.yaml
  od-8420: vision/detection/widerface/edgeai-mmdet/yolox_s_lite_640x640_20220307_model_config.yaml
  ss-8690: vision/segmentation/ade20k32/edgeai-tv/fpn_aspp_regnetx400mf_edgeailite_384x384_20210314_outby4_config.yaml
  ss-8610: vision/segmentation/ade20k32/edgeai-tv/deeplabv3plus_mobilenetv2_edgeailite_512x512_20210308_outby4_config.yaml
  ss-7618: vision/segmentation/ti-robokit/edgeai-tv/deeplabv3plus_mnetv2_edgeailite_robokit_768x432_qat-p2_config.yaml
  kd-7060: vision/keypoint/coco/edgeai-yolox/yolox_s_pose_ti_lite_640_20220301_model_config.yaml
  6dpose-7200: vision/object_6d_pose/ycbv/edgeai-yolox/yolox_s_object_pose_ti_lite_640x480_57p75_config.yaml
  visloc-7500: vision/visual_localization/carla/edgeai-tv/tiad_dkaze_carla_768x384_model_config.yaml
  cl-6090: vision/classification/imagenet1k/torchvision/mobilenet_v2_tv_config.yaml
  cl-6160: vision/classification/imagenet1k/torchvision/regnet_x_400mf_tv_config.yaml
  cl-6170: vision/classification/imagenet1k/torchvision/regnet_x_800mf_tv_config.yaml
  cl-6508: vision/classification/imagenet1k/edgeai-tv2/mobilenet_v2_lite_wt-v2_qat-v2-wc8-at8_20231120_model_config.yaml
  od-8210: vision/detection/coco/edgeai-mmdet/yolox_tiny_lite_416x416_20220217_model_config.yaml
  od-8270: vision/detection/coco/edgeai-mmdet/yolox_pico_lite_320x320_20230410_model_config.yaml
  od-8410: vision/detection/widerface/edgeai-mmdet/yolox_tiny_lite_416x416_20220318_model_config.yaml
  ss-8630: vision/segmentation/ade20k32/edgeai-tv/unet_aspp_mobilenetv2_edgeailite_512x512_20210306_outby2_config.yaml
  ss-8710: vision/segmentation/cocoseg21/edgeai-tv/deeplabv3plus_mobilenetv2_edgeailite_512x512_20210405_config.yaml
  ss-8720: vision/segmentation/cocoseg21/edgeai-tv/fpn_aspp_regnetx800mf_edgeailite_512x512_20210405_config.yaml
  cl-6010: vision/classification/imagenet1k/mlperf/resnet50_v1_shape_config.yaml
  cl-6480: vision/classification/imagenet1k/edgeai-tv/mobilenet_v3_lite_small_20210429_config.yaml
  cl-6490: vision/classification/imagenet1k/edgeai-tv/mobilenet_v3_lite_large_20210507_config.yaml
  cl-6100: vision/classification/imagenet1k/torchvision/resnet18_config.yaml
  cl-6110: vision/classification/imagenet1k/torchvision/resnet50_config.yaml
  od-8000: vision/detection/coco/mlperf/ssd_resnet34-ssd1200_config.yaml
  od-8040: vision/detection/coco/edgeai-mmdet/ssd_regnetx-200mf_fpn_bgr_lite_320x320_20201010_model_config.yaml
  cl-6488: vision/classification/imagenet1k/edgeai-tv/mobilenet_v3_lite_small_qat-p2_20210429_config.yaml
  cl-6098: vision/classification/imagenet1k/torchvision/mobilenet_v2_tv_qat-p2_config.yaml
  cl-6180: vision/classification/imagenet1k/torchvision/regnet_x_1_6gf_tv_config.yaml
  ss-8740: vision/segmentation/cocoseg21/edgeai-tv/lraspp_mobilenet_v3_large_lite_512x512_20210527_config.yaml
  de-7300: vision/depth_estimation/nyudepthv2/fast-depth/fast-depth_config.yaml
  de-7310: vision/depth_estimation/nyudepthv2/MiDaS/midas-small_config.yaml
  od-9202: vision/detection/coco/edgeai-mmdet/yolov7_l_coco_lite_640x640_20250109_model_config.yaml
  od-9203: vision/detection/coco/edgeai-mmdet/yolov7_l_coco_orig_640x640_20250109_model_config.yaml
  cl-6700: vision/classification/imagenet1k/hf-transformers/vit_tiny_patch16_224_simp_config.yaml
  cl-6701: vision/classification/imagenet1k/hf-transformers/vit_base_patch16_224_simp_config.yaml
  cl-6710: vision/classification/imagenet1k/hf-transformers/deit_tiny_patch16_224_simp_config.yaml
  cl-6711: vision/classification/imagenet1k/hf-transformers/deit_small_patch16_224_simp_config.yaml
  cl-6720: vision/classification/imagenet1k/hf-transformers/levit_128_224_simp_config.yaml
  cl-6721: vision/classification/imagenet1k/hf-transformers/levit_256_224_simp_config.yaml
  cl-6730: vision/classification/imagenet1k/hf-transformers/swin_tiny_patch4_window7_224_simp_config.yaml
  cl-6731: vision/classification/imagenet1k/hf-transformers/swin_small_patch4_window7_224_simp_config.yaml
  cl-6732: vision/classification/imagenet1k/hf-transformers/swin_base_patch4_window7_224_simp_config.yaml
  od-8920: vision/detection/coco/hf-transformers/detr_fb_resnet50_800x800_simp_config.yaml
  ss-8750: vision/segmentation/ade20k/hf-transformers/segformer_b0_finetuned_ade_512_512_simp_config.yaml
  ss-8760: vision/segmentation/ade20k/hf-transformers/segformer_b1_finetuned_ade_512_512_simp_config.yaml
  cl-6080: vision/classification/imagenet1k/torchvision/shufflenet_v2_x1.0_config.yaml
  ss-8700: vision/segmentation/ade20k32/edgeai-tv/fpn_aspp_regnetx800mf_edgeailite_512x512_20210312_outby4_config.yaml
  ss-8650: vision/segmentation/ade20k32/edgeai-tv/fpn_aspp_mobilenetv2_edgeailite_512x512_20210306_outby4_config.yaml
  ss-8670: vision/segmentation/ade20k32/edgeai-tv/fpn_aspp_mobilenetv2_1p4_edgeailite_512x512_20210307_outby4_config.yaml
  ss-8730: vision/segmentation/cocoseg21/edgeai-tv/deeplabv3_mobilenet_v3_large_lite_512x512_20210527_config.yaml
  cl-6500: vision/classification/imagenet1k/edgeai-tv2/mobilenet_v2_lite_wt-v2_20231101_model_config.yaml
  cl-6510: vision/classification/imagenet1k/edgeai-tv2/mobilenet_v3_large_lite_wt-v2_20231011_model_config.yaml
  cl-6530: vision/classification/imagenet1k/edgeai-tv2/resnet50_lite_wt-v2_20230919_config.yaml
  cl-6540: vision/classification/imagenet1k/edgeai-tv2/resnet101_lite_wt-v2_20230919_config.yaml
  cl-6550: vision/classification/imagenet1k/edgeai-tv2/resnext50_32x4d_lite_wt-v2_20230920_config.yaml
  cl-6560: vision/classification/imagenet1k/edgeai-tv2/resnext101_32x8d_lite_wt-v2_20230920_config.yaml
  cl-6570: vision/classification/imagenet1k/edgeai-tv2/regnet_x_1_6gf_lite_wt-v2_20230920_config.yaml
  cl-6580: vision/classification/imagenet1k/edgeai-tv2/regnet_x_400mf_lite_wt-v2_20230920_config.yaml
  cl-6590: vision/classification/imagenet1k/edgeai-tv2/regnet_x_800mf_lite_wt-v2_20230920_config.yaml
  cl-6600: vision/classification/imagenet1k/edgeai-tv2/mobilenet_v2_wt-v2_20240904_model_config.yaml
  od-8930: vision/detection/coco/mmdet/fcos_r50-caffe_fpn_gn-head_ms-640-800-2x_coco_config.yaml
  od-8940: vision/detection/coco/mmdet/centernet-update_r50-caffe_fpn_ms-1x_config.yaml
  od-8950: vision/detection/coco/mmdet/centernet_r18_crop512_config.yaml
  od-8970: vision/detection/coco/edgeai-mmdet/efficientdet_effb0_bifpn_lite_512x512_20240612_model_config.yaml
  od-9207: vision/detection/coco/edgeai-mmdet/rtmdet_m_coco_orig_640x640_20250310_model_config.yaml
  od-9206: vision/detection/coco/edgeai-mmdet/rtmdet_m_coco_lite_640x640_20250404_model_config.yaml
  od-9208: vision/detection/coco/edgeai-mmdet/rtmdet_l_coco_orig_640x640_20250310_model_config.yaml
  od-9209: vision/detection/coco/edgeai-mmdet/rtmdet_l_coco_lite_640x640_20250310_model_config.yaml
  kd-7070: vision/keypoint/coco/edgeai-mmpose/yoloxpose_tiny_lite_416x416_20240808_model_config.yaml
  kd-7080: vision/keypoint/coco/edgeai-mmpose/yoloxpose_s_lite_coco-640x640_20250119_model_config.yaml
  cl-0000: vision/classification/imagenet1k/mlperf/mobilenet_v1_1.0_224_config.yaml
  od-2020: vision/detection/coco/tf1-models/ssdlite_mobiledet_dsp_320x320_coco_20200519_config.yaml
  ss-2580: vision/segmentation/ade20k32/mlperf/deeplabv3_mnv2_ade20k32_float_config.yaml
  od-2010: vision/detection/coco/mlperf/ssd_mobilenet_v2_300_float_config.yaml
  cl-0160: vision/classification/imagenet1k/mlperf/resnet50_v1_config.yaml
  cl-0010: vision/classification/imagenet1k/tf1-models/mobilenet_v2_1.0_224_config.yaml
  cl-0130: vision/classification/imagenet1k/tf-tpu/efficientnet-lite0-fp32_config.yaml
  od-2000: vision/detection/coco/mlperf/ssd_mobilenet_v1_coco_20180128_config.yaml
  od-2080: vision/detection/coco/tf2-models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8_config.yaml
  od-2150: vision/detection/coco/google-automl/efficientdet_lite1_relu_config.yaml
  cl-0080: vision/classification/imagenet1k/mlperf/mobilenet_edgetpu_224_1.0_float_config.yaml
  cl-0140: vision/classification/imagenet1k/tf-tpu/efficientnet-lite4-fp32_config.yaml
  cl-0090: vision/classification/imagenet1k/tf-tpu/efficientnet-edgetpu-S_float_config.yaml
  od-2030: vision/detection/coco/tf1-models/ssdlite_mobiledet_edgetpu_320x320_coco_20200519_config.yaml
  cl-0200: vision/classification/imagenet1k/tf1-models/mobilenet_v2_float_1.4_224_config.yaml
  cl-0038: vision/classification/imagenet1k/tf1-models/inception_v1_224_quant_config.yaml
  cl-0040: vision/classification/imagenet1k/tf1-models/inception_v3_config.yaml
  cl-0170: vision/classification/imagenet1k/tf-tpu/efficientnet-lite1-fp32_config.yaml
  cl-0100: vision/classification/imagenet1k/tf-tpu/efficientnet-edgetpu-M_float_config.yaml
  od-2070: vision/detection/coco/tf2-models/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8_config.yaml
  cl-3090: vision/classification/imagenet1k/torchvision/mobilenet_v2_tv_config.yaml
  od-5120: vision/detection/coco/tf1-models/ssdlite_mobiledet_dsp_320x320_coco_20200519_config.yaml
  ss-5710: vision/segmentation/cocoseg21/edgeai-tv/deeplabv3plus_mobilenetv2_edgeailite_512x512_20210405_config.yaml
