task_type: depth_estimation
dataset_category: nyudepthv2
calibration_dataset: nyudepthv2
input_dataset: nyudepthv2
preprocess:
  resize:
  - 256
  - 256
  crop:
  - 256
  - 256
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 2
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 0.017125
  - 0.017507
  - 0.017429
  runtime_options:
    tensor_bits: 8
    accuracy_level: 1
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 1
    advanced_options:calibration_iterations: 1
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: 511, 983
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: 0
  model_path: midas-small.onnx
  model_id: de-7310
  input_details: null
  output_details: null
  num_inputs: 1
postprocess:
  save_output: false
metric: {}
model_info:
  metric_reference: {}
  model_shortlist: 50
