task_type: segmentation
dataset_category: ade20k
calibration_dataset: ade20k
input_dataset: ade20k
preprocess:
  resize:
  - 512
  - 512
  crop:
  - 512
  - 512
  data_layout: NHWC
  reverse_channels: false
  backend: cv2
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  target_device: null
  input_optimization: false
  input_data_layout: NHWC
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 0.017125
  - 0.017507
  - 0.017429
  runtime_options:
    tensor_bits: 8
    accuracy_level: 1
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 1
    advanced_options:calibration_iterations: 1
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: 0
  model_path: deeplabv3_mnv2_ade20k_train_20181203_512x512.tflite
  model_id: ss-2540
  input_details: null
  output_details: null
  num_inputs: 1
postprocess:
  save_output: false
model_info:
  metric_reference:
    accuracy_mean_iou%: 32.04
  model_shortlist: null
