task_type: visual_localization
dataset_category: ti-robokit_visloc_zed1hd
calibration_dataset: ti-robokit_visloc_zed1hd
input_dataset: ti-robokit_visloc_zed1hd
preprocess:
  resize:
  - 384
  - 768
  crop:
  - 384
  - 768
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 1
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.015625
  - 0.015625
  - 0.015625
  runtime_options:
    tensor_bits: 8
    accuracy_level: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 1
    advanced_options:calibration_iterations: 1
    advanced_options:quantization_scale_type: 1
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: 1
  model_path: tiad_dkaze_carla_768x384_model.onnx
  model_id: visloc-7500
  input_details: null
  output_details: null
  num_inputs: 1
postprocess: {}
model_info:
  metric_reference: {}
  model_shortlist: 10
